#[cfg(target_os = "linux")]
const LKH_BINARY: &[u8] = include_bytes!("../resources/LKH");

#[cfg(target_os = "windows")]
const LKH_BINARY: &[u8] = include_bytes!("../resources/LKH.exe");

use eframe::egui;
use egui::Ui;
use polars::prelude::*;
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

/* We're just going to focus on the csv -> TSP pipeline, no XLSX for now */

fn ingest_csv(path: &Path) -> PolarsResult<LazyFrame> {
    let file_path = PlRefPath::try_from_path(path)?;
    let lf = LazyCsvReader::new(file_path)
        .with_has_header(true)
        .finish()?;
    Ok(lf)
}

pub fn perform_dynamic_geocode_join(
    target_lf: LazyFrame,
    geo_df: DataFrame,
    user_zip_col: &str,
) -> PolarsResult<DataFrame> {
    target_lf
        .with_columns([col(user_zip_col)
            .cast(DataType::String)
            .str()
            .slice(lit(0), lit(5))])
        .left_join(
            geo_df
                .lazy()
                .with_columns([col("Zipcode").cast(DataType::String)]),
            col(user_zip_col),
            col("Zipcode"),
        )
        .collect()
}

fn load_zipcode_data() -> PolarsResult<DataFrame> {
    let geocode_file = env::var("geo_code").expect("Please check the encoded env variables");
    let file_path = PathBuf::from(geocode_file);
    let file = File::open(&file_path)?;
    let df = CsvReader::new(file).finish();
    df
}

pub fn df_to_tsp(
    geocoded_frame: PolarsResult<LazyFrame>,
    output_path: &Path,
    problem_name: &str,
) -> Result<(), String> {
    // 1. Extract the LazyFrame, collect it, and map any Polars errors to String
    let df: DataFrame = geocoded_frame
        .map_err(|e| e.to_string())
        .and_then(|lf| lf.collect().map_err(|e| e.to_string()))?;

    let dimension = df.height();
    if dimension == 0 {
        return Err("Something went wrong in the pipeline, See Rachel".to_string());
    }

    // 2. Extract columns safely. `column` returns a Result containing a &Series.
    let lat = df.column("Lat").map_err(|_| "Missing Lat".to_string())?;

    let lon = df.column("Lon").map_err(|_| "Missing Lon".to_string())?;

    // 3. Cast to f64 floats
    let lat_c = lat
        .f64()
        .map_err(|e| format!("Lat is not a valid float: {}", e))?;

    let lon_c = lon
        .f64()
        .map_err(|e| format!("Lon is not a valid float: {}", e))?;

    // 4. File I/O
    let mut file =
        File::create(output_path).map_err(|e| format!("Failed to create TSP file: {}", e))?;

    writeln!(file, "NAME : {}", problem_name).map_err(|e| e.to_string())?;
    writeln!(file, "TYPE : TSP").map_err(|e| e.to_string())?;
    writeln!(
        file,
        "COMMENT : Geocoded and Generated by Native Rust Pipeline"
    )
    .map_err(|e| e.to_string())?;
    writeln!(file, "DIMENSION : {}", dimension).map_err(|e| e.to_string())?;
    writeln!(file, "EDGE_WEIGHT_TYPE : GEO").map_err(|e| e.to_string())?;
    writeln!(file, "NODE_COORD_SECTION").map_err(|e| e.to_string())?;

    // 5. Write the coordinates
    let mut node_id = 1;
    for (lat_opt, lon_opt) in lat_c.into_iter().zip(lon_c.into_iter()) {
        if let (Some(lat), Some(lon)) = (lat_opt, lon_opt) {
            writeln!(file, "{} {:.6} {:.6}", node_id, lat, lon).map_err(|e| e.to_string())?;
            node_id += 1;
        }
    }

    writeln!(file, "EOF").map_err(|e| e.to_string())?;

    Ok(())
}

fn main() -> eframe::Result<()> {
    dotenvy::dotenv().ok();

    let options = eframe::NativeOptions::default();
    eframe::run_native(
        "TSP Pipeline GUI",
        options,
        Box::new(|_cc| Ok(Box::new(MyApp::default()))),
    )
}

struct MyApp {
    file_path: Option<PathBuf>,
    status_message: String,
    is_processing: bool,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            file_path: None,
            status_message: String::new(),
            is_processing: false,
        }
    }
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("TSP Pipeline - CSV to LKH");

            ui.horizontal(|ui| {
                ui.label("CSV File:");
                if let Some(path) = &self.file_path {
                    ui.label(path.display().to_string());
                } else {
                    ui.label("No file selected");
                }
            });

            // Drag and drop area
            let _drop_area = ui
                .label("Drag and drop a CSV file here")
                .on_hover_text("Drop a CSV file to load it");

            if ctx.input(|i| i.raw.hovered_files.len()) > 0 {
                ctx.input(|i| {
                    for file in &i.raw.hovered_files {
                        if let Some(path) = &file.path {
                            self.file_path = Some(path.clone());
                        }
                    }
                });
            }

            ui.separator();

            if ui.button("Run Pipeline").clicked() && !self.is_processing {
                if let Some(file_path) = &self.file_path {
                    self.is_processing = true;
                    let file_path = file_path.clone();

                    std::thread::spawn(move || match run_tsp_pipeline(&file_path) {
                        Ok(_) => {
                            println!("Pipeline completed successfully");
                        }
                        Err(e) => {
                            eprintln!("Pipeline error: {}", e);
                        }
                    });

                    self.status_message = "Pipeline started...".to_string();
                } else {
                    self.status_message = "Please select a CSV file first".to_string();
                }
            }

            ui.separator();
            ui.label(&self.status_message);
        });
    }

    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        // This method is required by the eframe::App trait
        // The main UI logic is implemented in the update method above
    }
}

fn run_tsp_pipeline(csv_path: &Path) -> Result<(), String> {
    // 1. Ingest CSV
    let lazy_frame = ingest_csv(csv_path).map_err(|e| format!("Failed to ingest CSV: {}", e))?;

    // 2. Load zipcode data
    let geo_df = load_zipcode_data().map_err(|e| format!("Failed to load geocode data: {}", e))?;

    // 3. Perform geocode join
    let geocoded = perform_dynamic_geocode_join(lazy_frame, geo_df, "Zipcode")
        .map_err(|e| format!("Failed to geocode: {}", e))?;

    // 4. Convert to TSP format
    let tsp_output = PathBuf::from("output.tsp");
    df_to_tsp(Ok(geocoded.lazy()), &tsp_output, "TSP.tsp")?;

    // 5. Write LKH binary to temp location
    let temp_lkh = PathBuf::from("/tmp/LKH");
    {
        let mut lkh_file =
            File::create(&temp_lkh).map_err(|e| format!("Failed to write LKH binary: {}", e))?;
        lkh_file
            .write_all(LKH_BINARY)
            .map_err(|e| format!("Failed to write LKH binary: {}", e))?;
        // lkh_file is dropped here at the end of the scope
    }

    #[cfg(target_os = "linux")]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&temp_lkh, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("Failed to set permissions: {}", e))?;
    }

    // 6. Run LKH
    let par_path = PathBuf::from("lkh_config.par");
    let mut par_file = File::create(&par_path).map_err(|e| e.to_string())?;
    writeln!(par_file, "PROBLEM_FILE = {}", tsp_output.display()).map_err(|e| e.to_string())?;

    let output = std::process::Command::new(&temp_lkh)
        .arg(&par_path)
        .output()
        .map_err(|e| format!("Failed to run LKH: {}", e))?;

    if !output.status.success() {
        return Err(format!(
            "LKH failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    println!("LKH output: {}", String::from_utf8_lossy(&output.stdout));

    Ok(())
}
