#[cfg(target_os = "linux")]
const LKH_BINARY: &[u8] = include_bytes!("../resources/LKH");

#[cfg(target_os = "macos")]
const LKH_BINARY: &[u8] = include_bytes!("../resources/LKH_mac");

#[cfg(target_os = "windows")]
const LKH_BINARY: &[u8] = include_bytes!("../resources/LKH.exe");

use eframe::egui;
use polars::prelude::*;
use std::env;
use std::fs::File;
use std::io::Cursor;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};

/* We're just going to focus on the csv -> TSP pipeline, no XLSX for now */

fn ingest_csv(path: &Path) -> PolarsResult<LazyFrame> {
    let file_path = PlRefPath::try_from_path(path)?;
    let lf = LazyCsvReader::new(file_path)
        .with_has_header(true)
        .finish()?;
    Ok(lf)
}

pub fn perform_dynamic_geocode_join(
    target_lf: LazyFrame,
    geo_df: DataFrame,
    user_zip_col: &str,
) -> PolarsResult<DataFrame> {
    target_lf
        .with_columns([col(user_zip_col)
            .cast(DataType::String)
            .str()
            .slice(lit(0), lit(5))])
        .left_join(
            geo_df
                .lazy()
                .with_columns([col("Zipcode").cast(DataType::String)]),
            col(user_zip_col),
            col("Zipcode"),
        )
        .collect()
}

fn load_zipcode_data() -> PolarsResult<DataFrame> {
    let csv_bytes = include_bytes!("../resources/Geocoding.csv");
    let cursor = Cursor::new(csv_bytes);
    let df = CsvReader::new(cursor).finish();
    df
}

pub fn df_to_tsp(
    geocoded_frame: PolarsResult<LazyFrame>,
    output_path: &Path,
    problem_name: &str,
) -> Result<(), String> {
    // 1. Extract the LazyFrame, collect it, and map any Polars errors to String
    let df: DataFrame = geocoded_frame
        .map_err(|e| e.to_string())
        .and_then(|lf| lf.collect().map_err(|e| e.to_string()))?;

    let dimension = df.height();
    if dimension == 0 {
        return Err("Something went wrong in the pipeline, See Rachel".to_string());
    }

    // 2. Extract columns safely. `column` returns a Result containing a &Series.
    let lat = df.column("Lat").map_err(|_| "Missing Lat".to_string())?;

    let lon = df.column("Lon").map_err(|_| "Missing Lon".to_string())?;

    // 3. Cast to f64 floats
    let lat_c = lat
        .f64()
        .map_err(|e| format!("Lat is not a valid float: {}", e))?;

    let lon_c = lon
        .f64()
        .map_err(|e| format!("Lon is not a valid float: {}", e))?;

    // 4. File I/O
    let mut file =
        File::create(output_path).map_err(|e| format!("Failed to create TSP file: {}", e))?;

    writeln!(file, "NAME : {}", problem_name).map_err(|e| e.to_string())?;
    writeln!(file, "TYPE : TSP").map_err(|e| e.to_string())?;
    writeln!(
        file,
        "COMMENT : Geocoded and Generated by Native Rust Pipeline"
    )
    .map_err(|e| e.to_string())?;
    writeln!(file, "DIMENSION : {}", dimension).map_err(|e| e.to_string())?;
    writeln!(file, "EDGE_WEIGHT_TYPE : GEO").map_err(|e| e.to_string())?;
    writeln!(file, "NODE_COORD_SECTION").map_err(|e| e.to_string())?;

    // 5. Write the coordinates
    let mut node_id = 1;
    for (lat_opt, lon_opt) in lat_c.into_iter().zip(lon_c.into_iter()) {
        if let (Some(lat), Some(lon)) = (lat_opt, lon_opt) {
            writeln!(file, "{} {:.6} {:.6}", node_id, lat, lon).map_err(|e| e.to_string())?;
            node_id += 1;
        }
    }

    writeln!(file, "EOF").map_err(|e| e.to_string())?;

    Ok(())
}

fn parse_lkh_output(
    output_file: &Path,
    all_coords: &Vec<[f64; 2]>,
) -> Result<Vec<[f64; 2]>, String> {
    let file = File::open(output_file).map_err(|e| format!("Failed to open LKH output: {}", e))?;
    let reader = BufReader::new(file);
    let mut route = Vec::new();
    let mut in_tour_section = false;

    for line in reader.lines() {
        let line = line.map_err(|e| format!("Failed to read line: {}", e))?;
        let trimmed = line.trim();

        if trimmed.starts_with("TOUR_SECTION") {
            in_tour_section = true;
            continue;
        }

        if trimmed == "-1" || trimmed == "EOF" {
            break;
        }

        if in_tour_section && !trimmed.is_empty() {
            if let Ok(node_id) = trimmed.parse::<usize>() {
                if let Some(coord) = all_coords.get(node_id - 1) {
                    route.push(*coord);
                }
            }
        }
    }

    if route.is_empty() {
        return Err("No tour found in LKH output".to_string());
    }

    Ok(route)
}

fn extract_coordinates_from_tsp(tsp_file: &Path) -> Result<Vec<[f64; 2]>, String> {
    let file = File::open(tsp_file).map_err(|e| format!("Failed to open TSP file: {}", e))?;
    let reader = BufReader::new(file);
    let mut coordinates: Vec<[f64; 2]> = Vec::new();
    let mut in_coord_section = false;

    for line in reader.lines() {
        let line = line.map_err(|e| format!("Failed to read line: {}", e))?;
        let trimmed = line.trim();

        if trimmed == "NODE_COORD_SECTION" {
            in_coord_section = true;
            continue;
        }

        if trimmed == "EOF" {
            break;
        }

        if in_coord_section && !trimmed.is_empty() {
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() >= 3 {
                if let (Ok(lat), Ok(lon)) = (parts[1].parse::<f64>(), parts[2].parse::<f64>()) {
                    coordinates.push([lon, lat]);
                }
            }
        }
    }

    Ok(coordinates)
}

fn main() -> eframe::Result<()> {
    dotenvy::dotenv().ok();

    let options = eframe::NativeOptions::default();
    eframe::run_native(
        "TSP Pipeline GUI",
        options,
        Box::new(|_cc| Ok(Box::new(MyApp::default()))),
    )
}

struct MyApp {
    file_path: Option<PathBuf>,
    status_message: String,
    is_processing: bool,
    route_coordinates: Vec<[f64; 2]>,
    all_coordinates: Vec<[f64; 2]>,
    show_route: bool,
}

impl Default for MyApp {
    fn default() -> Self {
        Self {
            file_path: None,
            status_message: String::new(),
            is_processing: false,
            route_coordinates: Vec::new(),
            all_coordinates: Vec::new(),
            show_route: false,
        }
    }
}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("TSP Pipeline - CSV to LKH");

            ui.horizontal(|ui| {
                ui.label("CSV File:");
                if let Some(path) = &self.file_path {
                    ui.label(path.display().to_string());
                } else {
                    ui.label("No file selected");
                }
            });

            // Drag and drop area
            let _drop_area = ui
                .label("Drag and drop a CSV file here")
                .on_hover_text("Drop a CSV file to load it");

            if ctx.input(|i| !i.raw.hovered_files.is_empty()) {
                ctx.input(|i| {
                    for file in &i.raw.hovered_files {
                        if let Some(path) = &file.path {
                            self.file_path = Some(path.clone());
                        }
                    }
                });
            }

            ui.separator();

            if ui.button("Run Pipeline").clicked() && !self.is_processing {
                if let Some(file_path) = &self.file_path {
                    self.is_processing = true;
                    let file_path = file_path.clone();

                    std::thread::spawn(move || match run_tsp_pipeline(&file_path) {
                        Ok((route_coords, all_coords)) => {
                            println!("Pipeline completed successfully");
                            // Store results in a temporary location that will be picked up on next UI update
                            std::fs::write(
                                "pipeline_result.json",
                                format!(
                                    r#"{{\"status\":\"success\",\"route_count\":{},\"coords_count\":{}}}"#,
                                    route_coords.len(),
                                    all_coords.len()
                                ),
                            )
                            .ok();
                        }
                        Err(e) => {
                            eprintln!("Pipeline error: {}", e);
                            std::fs::write(
                                "pipeline_result.json",
                                format!(r#"{{\"status\":\"error\",\"message\":\"{}\"}}"#, e),
                            )
                            .ok();
                        }
                    });

                    self.status_message = "Pipeline started...".to_string();
                } else {
                    self.status_message = "Please select a CSV file first".to_string();
                }
            }

            ui.separator();
            ui.label(&self.status_message);

            if self.is_processing {
                if let Ok(result_str) = std::fs::read_to_string("pipeline_result.json") {
                    self.is_processing = false;
                    if result_str.contains("\"status\":\"success\"") {
                        self.status_message = "Pipeline completed successfully".to_string();
                        let tsp_path = std::path::PathBuf::from("output.tsp");
                        let tour_path = std::path::PathBuf::from("output.tour");
                        if let Ok(all_coords) = extract_coordinates_from_tsp(&tsp_path) {
                            if let Ok(route) = parse_lkh_output(&tour_path, &all_coords) {
                                self.all_coordinates = all_coords;
                                self.route_coordinates = route;
                                self.show_route = true;
                            }
                        }
                    } else {
                        self.status_message = "Pipeline failed".to_string();
                    }
                    let _ = std::fs::remove_file("pipeline_result.json");
                } else {
                    ctx.request_repaint();
                }
            }

            if self.show_route && !self.route_coordinates.is_empty() {
                ui.separator();
                ui.heading("Route computed");
                ui.label(format!(
                    "Total points: {} | Route points: {}",
                    self.all_coordinates.len(),
                    self.route_coordinates.len()
                ));
            }
        });
    }

    fn ui(&mut self, _ui: &mut egui::Ui, _frame: &mut eframe::Frame) {}
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PipelineStage {
    Idle,
    IngestCsv,
    LoadGeocodes,
    GeocodeJoin,
    WriteTsp,
    RunLkh,
    ParseTour,
    Done,
}

fn run_tsp_pipeline(csv_path: &Path) -> Result<(Vec<[f64; 2]>, Vec<[f64; 2]>), String> {
    // 1. Ingest CSV
    println!("[pipeline] stage={:?}", PipelineStage::IngestCsv);
    let lazy_frame = ingest_csv(csv_path).map_err(|e| format!("Failed to ingest CSV: {}", e))?;

    // 2. Load zipcode data
    println!("[pipeline] stage={:?}", PipelineStage::LoadGeocodes);
    let geo_df = load_zipcode_data().map_err(|e| format!("Failed to load geocode data: {}", e))?;

    // 3. Perform geocode join
    println!("[pipeline] stage={:?}", PipelineStage::GeocodeJoin);
    let geocoded = perform_dynamic_geocode_join(lazy_frame, geo_df, "Zipcode")
        .map_err(|e| format!("Failed to geocode: {}", e))?;

    // 4. Convert to TSP format
    println!("[pipeline] stage={:?}", PipelineStage::WriteTsp);
    let tsp_output = PathBuf::from("output.tsp");
    df_to_tsp(Ok(geocoded.lazy()), &tsp_output, "TSP.tsp")?;

    // Extract coordinates from TSP file for visualization
    let all_coordinates = extract_coordinates_from_tsp(&tsp_output)?;

    // 5. Write LKH binary to temp location
    #[cfg(target_os = "linux")]
    let temp_lkh = PathBuf::from("/tmp/LKH");
    #[cfg(target_os = "windows")]
    let temp_lkh = PathBuf::from("LKH.exe");
    #[cfg(target_os = "macos")]
    let temp_lkh = PathBuf::from("/tmp/LKH_mac");

    {
        let mut lkh_file =
            File::create(&temp_lkh).map_err(|e| format!("Failed to write LKH binary: {}", e))?;
        lkh_file
            .write_all(LKH_BINARY)
            .map_err(|e| format!("Failed to write LKH binary: {}", e))?;
        // lkh_file is dropped here at the end of the scope
    }

    #[cfg(target_os = "linux")]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&temp_lkh, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("Failed to set permissions: {}", e))?;
    }

    // 6. Run LKH
    println!("[pipeline] stage={:?}", PipelineStage::RunLkh);
    let par_path = PathBuf::from("lkh_config.par");
    let tour_output = PathBuf::from("output.tour");
    let mut par_file = File::create(&par_path).map_err(|e| e.to_string())?;
    writeln!(par_file, "PROBLEM_FILE = {}", tsp_output.display()).map_err(|e| e.to_string())?;
    writeln!(par_file, "RUNS = 1").map_err(|e| e.to_string())?;
    writeln!(par_file, "TOUR_FILE = {}", tour_output.display()).map_err(|e| e.to_string())?;

    let output = std::process::Command::new(&temp_lkh)
        .arg(&par_path)
        .output()
        .map_err(|e| format!("Failed to run LKH: {}", e))?;

    // Note: LKH may write a valid TOUR_FILE even when it exits with a non-zero status.
    // In that case, prefer validating existence/non-empty TOUR_FILE over process status.
    if !output.status.success() {
        if tour_output.metadata().map(|m| m.len() > 0).unwrap_or(false) {
            eprintln!(
                "[pipeline] LKH exited with status {:?}, but '{}' was produced (non-empty). Continuing.",
                output.status.code(),
                tour_output.display()
            );
        } else {
            return Err(format!(
                "LKH failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }
    }

    println!("LKH output: {}", String::from_utf8_lossy(&output.stdout));

    // 7. Parse LKH output to get route
    println!("[pipeline] stage={:?}", PipelineStage::ParseTour);
    let route_coordinates = parse_lkh_output(&tour_output, &all_coordinates)?;

    println!("[pipeline] stage={:?}", PipelineStage::Done);
    Ok((route_coordinates, all_coordinates))
}
